[metadata]
name = hadolint_coatl
version = 2.15.0
description = Python wrapper around invoking hadolint (https://github.com/hadolint/hadolint)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/coatl-dev/hadolint-coatl
author = César Román
author_email = cesar@coatl.dev
license = MIT
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
project_urls =
    Funding = https://github.com/sponsors/cesarcoatl
    Source = https://github.com/coatl-dev/hadolint-coatl
    Tracker = https://github.com/coatl-dev/hadolint-coatl/issues

[options]
python_requires = >=3.10
setup_requires =
    setuptools-download

[setuptools_download]
download_scripts =
    [hadolint]
    group = hadolint-binary
    marker = sys_platform == "linux" and platform_machine == "aarch64"
    url = https://github.com/hadolint/hadolint/releases/download/v2.15.0/hadolint-linux-arm64
    sha256 = 17993abf41a0a4da7f2e08970b4f4baf3f95e5e79b9ac80ba6b2aac1960ca71c
    [hadolint]
    group = hadolint-binary
    marker = sys_platform == "linux" and platform_machine == "x86_64"
    url = https://github.com/hadolint/hadolint/releases/download/v2.15.0/hadolint-linux-x86_64
    sha256 = eb8eb4dd06a068cce65cb84743fba69f09ed12a36ff13d58f9af090d6d696970
    [hadolint]
    group = hadolint-binary
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/hadolint/hadolint/releases/download/v2.15.0/hadolint-macos-arm64
    sha256 = 1d701a41d2760ec88f8eff8d93f78b743d6ed57c53146ef274dbeb540816e563
    [hadolint.exe]
    group = hadolint-binary
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    marker = sys_platform == "win32" and platform_machine == "ARM64"
    marker = sys_platform == "cygwin" and platform_machine == "x86_64"
    url = https://github.com/hadolint/hadolint/releases/download/v2.15.0/hadolint-windows-x86_64.exe
    sha256 = 8a155b50a75d7afb26a03bd29e7c67f32d83f2e5992d918010b1832fcb5866c6
