[metadata]
name = hadolint_coatl
version = 2.15.1
description = Python wrapper around invoking hadolint (https://github.com/hadolint/hadolint)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/coatl-dev/hadolint-coatl
author = César Román
author_email = cesar@coatl.dev
license = MIT
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
project_urls =
    Funding = https://github.com/sponsors/cesarcoatl
    Source = https://github.com/coatl-dev/hadolint-coatl
    Tracker = https://github.com/coatl-dev/hadolint-coatl/issues

[options]
python_requires = >=3.10
setup_requires =
    setuptools-download

[setuptools_download]
download_scripts =
    [hadolint]
    group = hadolint-binary
    marker = sys_platform == "linux" and platform_machine == "aarch64"
    url = https://github.com/hadolint/hadolint/releases/download/v2.15.1/hadolint-linux-arm64
    sha256 = f6198ef8090f404dbb771abfee086eb8c48ac177f30da7fd3510aca35b344b5d
    [hadolint]
    group = hadolint-binary
    marker = sys_platform == "linux" and platform_machine == "x86_64"
    url = https://github.com/hadolint/hadolint/releases/download/v2.15.1/hadolint-linux-x86_64
    sha256 = c7187db94eeeeca956519a6af171adc31453941a1e777961f6e680f697c8c507
    [hadolint]
    group = hadolint-binary
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/hadolint/hadolint/releases/download/v2.15.1/hadolint-macos-arm64
    sha256 = 5c09f3213f8e40406abe048233d985eebef336d4a6a20021be47fadb6cf480a2
    [hadolint.exe]
    group = hadolint-binary
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    marker = sys_platform == "win32" and platform_machine == "ARM64"
    marker = sys_platform == "cygwin" and platform_machine == "x86_64"
    url = https://github.com/hadolint/hadolint/releases/download/v2.15.1/hadolint-windows-x86_64.exe
    sha256 = 01d927294962b5387f9ead4f18679158452be4f17c765ad0bdffe5264b9c7b0a
