name: ci

on:
  pull_request:
  push:
    branches:
      - coatl

jobs:
  linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.6.0
    with:
      env: '["py38"]'
      os: ubuntu-latest
  macos:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.6.0
    with:
      env: '["py38"]'
      os: macos-latest
      wheel-tags: true
  windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.6.0
    with:
      env: '["py38"]'
      os: windows-latest
      wheel-tags: true
